"""remove_confidence_and_processing_time

Revision ID: 2d9bcb27492f
Revises: 8d3a8a3b4332
Create Date: 2026-07-02 11:55:28.320006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9bcb27492f'
down_revision: Union[str, None] = '8d3a8a3b4332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_results', 'processing_time_ms')
    op.drop_column('extraction_results', 'confidence_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_results', sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('extraction_results', sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
