"""Add SAP fields

Revision ID: 8d3a8a3b4332
Revises: 96c481317477
Create Date: 2026-06-22 16:49:38.060280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d3a8a3b4332'
down_revision: Union[str, None] = '96c481317477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('sap_sync_status', sa.Enum('pending', 'success', 'failed', name='sapsyncstatus'), nullable=True))
    op.add_column('documents', sa.Column('sap_document_no', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('sap_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('sap_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('sap_error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'sap_error_message')
    op.drop_column('documents', 'sap_synced_at')
    op.drop_column('documents', 'sap_response')
    op.drop_column('documents', 'sap_document_no')
    op.drop_column('documents', 'sap_sync_status')
    # ### end Alembic commands ###
