"""remove_sap_fields

Revision ID: ee8a607096e2
Revises: 2d9bcb27492f
Create Date: 2026-07-07 14:14:40.600070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee8a607096e2'
down_revision: Union[str, None] = '2d9bcb27492f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'sap_synced_at')
    op.drop_column('documents', 'sap_response')
    op.drop_column('documents', 'sap_sync_status')
    op.drop_column('documents', 'sap_document_no')
    op.drop_column('documents', 'sap_error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('sap_error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('sap_document_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('sap_sync_status', postgresql.ENUM('pending', 'success', 'failed', name='sapsyncstatus'), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('sap_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('sap_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
